#!/bin/bash

make(){
    rm -rf dist
    tsc
    cp LICENSE ./dist/
    cp package.json ./dist/
    cp README.md ./dist/
}

publish(){
    make
    cd dist
    npm publish
    sed -i "s/\"registry.*/\"registry\":\"http:\/\/npm.inner:8081\/repository\/private\/\"/g" ./package.json
    npm publish
}

$1